
CC=gcc

CFLAGS= -Wall \
-O0



posix_mq:posix_mq.c
	$(CC) $(CFLAGS)  -o posixmq   posixmq.c -lpthread -lrt


heap_mq:heap_mq.c
	$(CC) $(CFLAGS)  -o heapmq   heapmq.c -lpthread -lrt

#PHONY target to remove the executables
.PHONY:clean
clean:
	rm heap_mq posix_mq