INCLUDES =	-I/usr/local/opencv/include

CC=	g++

CFLAGS=	-O0	-g	$(INCLUDES) 

LIBS=	-lrt

CPPLIBS=	-L/usr/local/opencv/lib	-lopencv_core	-lopencv_flann	-lopencv_video

build:	jitter

clean:
	-rm	-f	*.o	*.d
	
	-rm	-f	jitter

jitter:	jitter.o
	$(CC)	$(CFLAGS)	$(INCLUDES)	-o 	jitter	jitter.o	`pkg-config	--libs	opencv`	$(CPPLIBS)	-lpthread
	