	($(PLATFORM),HOST)
	CC=gcc
	flags=		


	cfiles=	posix_clock.c		

	CCFLAGS=	$(flags)	-g	-O3	-lpthread	-lrt	
	
.PHONY:	compile-all	clean	build	

build:	posix_clock.o		
	$(CC)	-o	posix_clock.o	$(CCFLAGS)

compile-all:	$(cfiles)	
	$(CC)	-c	$(cfiles)	$(CCFLAGS)

posix_clock.o:	posix_clock.c			
	$(CC)	-c	posix_clock.c	$(CCFLAGS)	

posix_clock.i:	posix_clock.c	
	$(CC)	-E	posix_clock.c	$(CCFLAGS)	

posix_clock.asm:	posix_clock.c		
	$(CC)	-S	posix_clock.c	$(CCFLAGS)		


clean :
	rm	-f	*.o	*.s	*.e	